<font size="5">FTS Stokesian dynamics: hard coded

In [1]:
from ftssdhc import FTShc
import numpy as np, matplotlib.pyplot as plt

In [2]:
# particle radius, self-propulsion speed, number and fluid viscosity
b, Np, eta = 0.3, 2, 0.1
ftshc = FTShc(b, Np, eta)

In [3]:
%%time
## Two spheres falling next to each other: FTS

#initial position
r = np.array([0.,2.3, 0.,0., 100.,100.])

#gravity in neg z direction
F = np.array([0.,0., 0.,0., -0.,-1.])
T = np.array([0.,0., 0.,1.,  0., 0.])  ##torque

# integration parameters
Nt=2; r1=np.zeros([3,Nt]); r2=np.zeros([3,Nt])
r1[:,0] = r[::Np]; r2[:,0] = r[1::Np]
dt=3.;
v = np.zeros(3*Np);
o = np.zeros(3*Np)
theta1=np.zeros([3,Nt]); theta2=np.zeros([3,Nt])
v1 = np.zeros([3,Nt-1]); v2 = np.zeros([3,Nt-1])
o1 = np.zeros([3,Nt-1]); o2 = np.zeros([3,Nt-1])

for i in range(Nt-1):
    ftshc.directSolve(v, o, r, F, T)
    
    r1[:,i+1] = r1[:,i] + dt*v[::Np]
    r2[:,i+1] = r2[:,i] + dt*v[1::Np]
    
    theta1[:,i+1] = theta1[:,i] + dt*o[::Np]
    theta2[:,i+1] = theta2[:,i] + dt*o[1::Np]
    
    #get velocity (constant for this case)
    v1[:,i] = v[::Np]
    v2[:,i] = v[1::Np]
    
    #get angular velocity (constant for this case)
    o1[:,i] = o[::Np]
    o2[:,i] = o[1::Np]
    
    # reset variables for next time step
    r[::Np] = r1[:,i+1]
    r[1::Np] = r2[:,i+1]
    v = v*0
    o = o*0

print('finish')

finish
CPU times: user 3.34 ms, sys: 0 ns, total: 3.34 ms
Wall time: 2.52 ms


In [4]:
## velocity and angular velocity of particle 1
v1[:,0], o1[:,0]

(array([ 0.        ,  0.        , -0.09974163]),
 array([0.        , 0.05886391, 0.        ]))

In [5]:
## velocity and angular velocity of particle 2
v2[:,0], o2[:,0]

(array([ 0.       ,  0.       , -1.7704632]),
 array([ 0.        , 14.68685653,  0.        ]))

___________

<font size="5">FTS Stokesian dynamics: autograd

In [6]:
from ftssd import FTS
import autograd.numpy as np, matplotlib.pyplot as plt

In [7]:
fts = FTS(b, Np, eta)

In [8]:
%%time
## Two spheres falling next to each other: FTS

#initial position
r = np.array([0.,2.3, 0.,0., 100.,100.])

#gravity in neg z direction
F = np.array([0.,0., 0.,0., -0.,-1.])
T = np.array([0.,0., 0.,1.,  0., 0.])  ##torque

# integration parameters
Nt=2; r1=np.zeros([3,Nt]); r2=np.zeros([3,Nt])
r1[:,0] = r[::Np]; r2[:,0] = r[1::Np]
dt=3.;
v = np.zeros(3*Np);
o = np.zeros(3*Np)
theta1=np.zeros([3,Nt]); theta2=np.zeros([3,Nt])
v1 = np.zeros([3,Nt-1]); v2 = np.zeros([3,Nt-1])
o1 = np.zeros([3,Nt-1]); o2 = np.zeros([3,Nt-1])

for i in range(Nt-1):
    fts.directSolve(v, o, r, F, T)
    
    r1[:,i+1] = r1[:,i] + dt*v[::Np]
    r2[:,i+1] = r2[:,i] + dt*v[1::Np]
    
    theta1[:,i+1] = theta1[:,i] + dt*o[::Np]
    theta2[:,i+1] = theta2[:,i] + dt*o[1::Np]
    
    #get velocity (constant for this case)
    v1[:,i] = v[::Np]
    v2[:,i] = v[1::Np]
    
    #get angular velocity (constant for this case)
    o1[:,i] = o[::Np]
    o2[:,i] = o[1::Np]
    
    # reset variables for next time step
    r[::Np] = r1[:,i+1]
    r[1::Np] = r2[:,i+1]
    v = v*0
    o = o*0

print('finish')

finish
CPU times: user 4.3 s, sys: 0 ns, total: 4.3 s
Wall time: 4.29 s


In [9]:
## velocity and angular velocity of particle 1
v1[:,0], o1[:,0]

(array([ 0.        ,  0.        , -0.09974163]),
 array([0.        , 0.05886391, 0.        ]))

In [10]:
## velocity and angular velocity of particle 2
v2[:,0], o2[:,0]

(array([ 0.       ,  0.       , -1.7704632]),
 array([ 0.        , 14.68685653,  0.        ]))

--------------------------------

<font size="5">PyStokes (superposition approximation)

In [11]:
import pystokes

In [12]:
pstk = pystokes.unbounded.Rbm(b, Np, eta)

In [13]:
%%time
## Two spheres falling next to each other: pystokes

#initial position
r = np.array([0.,2.3, 0.,0., 100.,100.])

#gravity in neg z direction
F = np.array([0.,0., 0.,0., -0.,-1.])
T = np.array([0.,0., 0.,1.,  0., 0.])  ##torque

# integration parameters
Nt=2; r1=np.zeros([3,Nt]); r2=np.zeros([3,Nt])
r1[:,0] = r[::Np]; r2[:,0] = r[1::Np]
dt=3.;
v = np.zeros(3*Np);
o = np.zeros(3*Np)
theta1=np.zeros([3,Nt]); theta2=np.zeros([3,Nt])
v1_pstk = np.zeros([3,Nt-1]); v2_pstk = np.zeros([3,Nt-1])
o1_pstk = np.zeros([3,Nt-1]); o2_pstk = np.zeros([3,Nt-1])

for i in range(Nt-1):
    pstk.mobilityTT(v, r, F)
    pstk.mobilityTR(v, r, T)
    pstk.mobilityRT(o, r, F)
    pstk.mobilityRR(o, r, T)
    
    r1[:,i+1] = r1[:,i] + dt*v[::Np]
    r2[:,i+1] = r2[:,i] + dt*v[1::Np]
    
    theta1[:,i+1] = theta1[:,i] + dt*o[::Np]
    theta2[:,i+1] = theta2[:,i] + dt*o[1::Np]
    
    #get velocity (constant for this case)
    v1_pstk[:,i] = v[::Np]
    v2_pstk[:,i] = v[1::Np]
    
    #get angular velocity (constant for this case)
    o1_pstk[:,i] = o[::Np]
    o2_pstk[:,i] = o[1::Np]
    
    # reset variables for next time step
    r[::Np] = r1[:,i+1]
    r[1::Np] = r2[:,i+1]
    v = v*0
    o = o*0

print('finish')

finish
CPU times: user 169 ms, sys: 105 µs, total: 170 ms
Wall time: 27.8 ms


In [14]:
## velocity and angular velocity of particle 1
v1_pstk[:,0], o1_pstk[:,0]

(array([ 0.        ,  0.        , -0.09974163]),
 array([0.        , 0.05886391, 0.        ]))

In [15]:
## velocity and angular velocity of particle 2
v2_pstk[:,0], o2_pstk[:,0]

(array([ 0.        ,  0.        , -1.76838826]),
 array([ 0.       , 14.7365688,  0.       ]))