In [1]:
import numpy as np

In [4]:
np.diag(np.block([np.full(2, 0.1), np.full(1, 0.2), np.full(2, 0.3), np.full(3, 0.4)]))

array([[0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.3, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.3, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.4, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.4]])

In [15]:
([np.full(2, 0.1), np.full(1, 0.2), np.full(2, 0.3), np.full(3, 0.4)])

[array([0.1, 0.1]), array([0.2]), array([0.3, 0.3]), array([0.4, 0.4, 0.4])]

In [19]:
np.tile(np.array([2,1]),2)

array([2, 1, 2, 1])

In [21]:
np.concatenate([np.full(2, 0.1), np.full(1, 0.2), np.full(2, 0.3), np.full(3, 0.4)])

array([0.1, 0.1, 0.2, 0.3, 0.3, 0.4, 0.4, 0.4])

In [24]:
a[:] = (1,2,2)
a

array([1, 2, 2])