In [1]:
import numpy as np

In [2]:
np.diag(np.block([np.full(2, 0.1), np.full(1, 0.2), np.full(2, 0.3), np.full(3, 0.4)]))

array([[0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.3, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.3, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.4, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.4]])

In [3]:
([np.full(2, 0.1), np.full(1, 0.2), np.full(2, 0.3), np.full(3, 0.4)])

[array([0.1, 0.1]), array([0.2]), array([0.3, 0.3]), array([0.4, 0.4, 0.4])]

In [4]:
np.tile(np.array([2,1]),2)

array([2, 1, 2, 1])

In [5]:
np.concatenate([np.full(2, 0.1), np.full(1, 0.2), np.full(2, 0.3), np.full(3, 0.4)])

array([0.1, 0.1, 0.2, 0.3, 0.3, 0.4, 0.4, 0.4])

In [6]:
np.diagonal(np.array([[ 0,1,3],
                      [1,2,3],
                      [3,4,4]]))

array([0, 2, 4])

In [10]:
np.tile(np.array([1,2,3]),2)

array([1, 2, 3, 1, 2, 3])

In [ ]:
1.2